# Generated by Django 3.0.8 on 2020-07-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('ingredients', models.TextField()),
                ('score_grade', models.CharField(max_length=3)),
                ('stores', models.CharField(max_length=200)),
                ('brands', models.TextField()),
                ('link', models.TextField()),
                ('pictures', models.CharField(default='', max_length=200)),
                ('nutrition_score_100', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitute.Products')),
            ],
        ),
    ]
