# Generated by Django 3.0.8 on 2020-07-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(unique=True)),
                ('ingredients', models.TextField()),
                ('score_grade', models.TextField()),
                ('stores', models.TextField()),
                ('brands', models.TextField()),
                ('link', models.TextField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitute.categories')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=155)),
                ('password', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='user_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitute.products')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitute.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
