# Generated by Django 3.0.8 on 2020-07-09 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0002_auto_20200708_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pictures',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitute.Categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='score_grade',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='products',
            name='stores',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_record',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitute.Products'),
        ),
        migrations.AlterField(
            model_name='user_record',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitute.User'),
        ),
    ]
