# Generated by Django 3.0.8 on 2020-07-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0005_auto_20200709_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitute.Categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user_record',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitute.Products'),
        ),
        migrations.AlterField(
            model_name='user_record',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitute.User'),
        ),
    ]
