# Generated by Django 3.0.8 on 2020-07-28 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200728_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscribeemail',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
